global:
  imagePullPolicy: IfNotPresent
  relname: default

storage:
  name: tensorflow-fs
  accessMode: ReadWriteMany
  pv: 
    capacity: "1Gi"
  pvc:
    name: ext-storage
    request: "750M"

tfCluster:
  deploy: true
  service:
    name: tensorflow-cluster
    internalPort: 8080
    externalPort: 8080
    type: ClusterIP
  image: 
    repo: zubrabubra
    name: flowers-viktor:latest
  settings:
    jobs: 
      ps: 1
      worker: 2
  resources:
    requests:
      cpu: 1000m
      memory: 1Gb
    limits:
      cpu: 2000m
      memory: 2Gb
